server:
  port: 10011
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #指定配置文件的存放位置
          search-locations: classpath:/pro
      fail-fast: true #快速失败:


#客户端连接上了eureka服务端
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:10010/eureka/

#actuator设置
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点,默认是info和health
  endpoint:
    health:
      show-details: always #默认是never

